[package]
name = "wson"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["wat-aro <kazutas1008@gmail.com>"]
description = "JSON parser made with nom"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
